version: "3.8"
services:
  api:
    build: ./
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb://db/starbucks_db
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - app:/data/db
    restart: always

volumes:
  app:
  