<<<<<<< HEAD
version: "3.8"

services:
  api:
    build: ./
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb://db/starbucks_db
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - app:/data/db
    restart: always

volumes:
  app:
=======
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: david
      MONGO_INITDB_ROOT_PASSWORD: david

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: david
      ME_CONFIG_MONGODB_ADMINPASSWORD: david
      ME_CONFIG_MONGODB_URL: mongodb://david:david@mongo:27017/
  app:
    depends_on:
      - mongo
    image: anas149037/starbucksdavid:1.1
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

      
volumes:
  db:
>>>>>>> 68b76576aec65f7bbd0e6f1e4b93245222299a85
